### ISSUE TITLE
Searched songs not working

### ISSUE THREAD

**Issue by JoshMayberry** [daviirodrig/EternalJukebox#3]
### Description
Not able to search and play songs

### Console Logs
/api/profile/me:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
jukebox_go.html?id=2bEb7Vc12aL7e6BbXbGW2a:1339 Could not retrieve stars: 
/api/audio/jukebox/2bEb7Vc12aL7e6BbXbGW2a:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
jremix.js?version=1-1-1:1 audio error DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data
jukebox_go.html:1 Uncaught (in promise) DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data

### Song
Lieblingslied by mia diekow: https://www.eternalboxmirror.xyz/jukebox_go.html?id=2bEb7Vc12aL7e6BbXbGW2a

### Additional Information
Your site rocks! I'm excited for when it is working again. :D

**Comment by daviirodrig** [comment]
I do not own eternalboxmirror.xyz, I noticed they use my code but I cant provide support for that, you can try to use my host if you want https://jukebox.davi.gq

**Comment by JoshMayberry** [comment]
lol. That's annoying that they just took your code.
It works as intended on your site.
